# Generated by Django 3.1.2 on 2020-10-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='category/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('builder_name', models.CharField(max_length=50, null=True)),
                ('owner_type', models.CharField(choices=[('Agent', 'agent'), ('Owner', 'owner')], max_length=10, null=True)),
                ('property_type', models.CharField(choices=[('Sale', 'sale'), ('Rent', 'rent')], max_length=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('website', models.URLField(null=True)),
                ('floor', models.PositiveIntegerField(null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='propertyprofile_pic/')),
                ('property_image', models.ImageField(null=True, upload_to='property_image/')),
                ('experience', models.PositiveIntegerField(null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('phone_number_1', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('description', models.TextField(null=True)),
                ('short_description', models.TextField(null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('swimming_pool', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('gym', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('fire_fighting_system', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('club_house', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('jogging_and_strolling', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('reservred_parking', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('power_backup', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('bank_and_atm', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('security', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('earthquake_resistant', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('intercom', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('rainwater_harvesting', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('lift', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('visitor_parking', models.CharField(choices=[('Available', 'availbale'), ('Not available ', 'Not available'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('posession_status', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('Septmber', 'Septmber'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('Ready to move', 'Ready to move'), ('Not applicable', 'Not applicable')], max_length=20, null=True)),
                ('posession_year', models.PositiveIntegerField(null=True)),
                ('no_of_towers', models.PositiveIntegerField(null=True)),
                ('no_of_units', models.PositiveIntegerField(null=True)),
                ('project_area', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rera_no', models.CharField(max_length=100, null=True)),
                ('facebook_link', models.URLField(null=True)),
                ('instagram_link', models.URLField(null=True)),
                ('youtube_link', models.URLField(null=True)),
                ('units_sold', models.PositiveIntegerField()),
                ('units_available', models.PositiveIntegerField()),
                ('total_units', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.category')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projectproperty/')),
                ('image_title', models.CharField(max_length=50, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
            },
        ),
        migrations.CreateModel(
            name='Propertyarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_configrations', models.CharField(choices=[('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK'), ('5 BHK', '5 BHK'), ('1,2 BHK', '1,2 BHK'), ('1,2,3 BHK', '1,2,3 BHK'), ('1,2,3,4 BHK', '1,2,3,4 BHK'), ('1,2,3,4,5 BHK', '1,2,3,4,5 BHK')], max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='propertyfloor_plan/')),
                ('floor_plan_title', models.CharField(max_length=50, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'verbose_name': 'Property area',
                'verbose_name_plural': 'Property areas',
            },
        ),
        migrations.CreateModel(
            name='BuildersOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='PropertyOffice/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'verbose_name': 'BuilderOffice',
                'verbose_name_plural': 'BuildersOffice',
            },
        ),
        migrations.CreateModel(
            name='Banks_approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banks_approved', models.CharField(choices=[('Axis Bank', 'Axis Bank'), ('Bandhan Bank', 'Bandhan Bank'), ('CSB Bank', 'CSB Bank'), ('City Union Bank', 'City Union Bank'), ('DCB Bank', 'DCB Bank'), ('Dhanlaxmi Bank', 'Dhanlaxmi Bank'), ('Federal Bank', 'Federal Bank'), ('HDFC Bank', 'HDFC Bank'), ('ICICI Bank', 'ICICI Bank'), ('IDBI Bank', 'IDBI Bank'), ('IDFC First Bank', 'IDFC First Bank'), ('IndusInd Bank', 'IndusInd Bank'), ('Karnataka Bank', 'Ready to move'), ('Karur Vysya Bank', 'Karur Vysya Bank'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('Lakshmi Vilas Bank', 'Lakshmi Vilas Bank'), ('Nainital Bank', 'Nainital Bank'), ('RBL Bank', 'RBL Bank'), ('South Indian Bank', 'South Indian Bank'), ('Tamilnad Mercantile Bank Limited', 'Tamilnad Mercantile Bank Limited'), ('Yes Bank', 'Yes Bank')], max_length=50, null=True)),
                ('loan_details', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'verbose_name': 'Bank approved',
                'verbose_name_plural': 'Banks approved',
            },
        ),
    ]
