# Generated by Django 3.1.2 on 2020-10-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='categoryprofessionals/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('projects_completed', models.PositiveIntegerField()),
                ('happy_customers', models.PositiveIntegerField()),
                ('max_budget', models.PositiveIntegerField()),
                ('min_budget', models.PositiveIntegerField()),
                ('profile_image', models.ImageField(null=True, upload_to='profile/')),
                ('banner_image', models.ImageField(null=True, upload_to='banner/')),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('short_description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('phone_number_1', models.CharField(max_length=15, null=True)),
                ('website', models.URLField(null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('facebook_link', models.URLField(null=True)),
                ('instagram_link', models.URLField(null=True)),
                ('youtube_link', models.URLField(null=True)),
                ('experience', models.PositiveIntegerField(null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professionals.category')),
            ],
            options={
                'verbose_name': 'Professional',
                'verbose_name_plural': 'Professionals',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='proprojectimages/')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professionals')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ProfessionalOffice/')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professionals')),
            ],
            options={
                'verbose_name': 'ProfessionalOffice',
                'verbose_name_plural': 'ProfessionalOffices',
            },
        ),
    ]
