# Generated by Django 3.1.2 on 2020-10-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('banner_image1', models.ImageField(null=True, upload_to='home_banner/')),
                ('banner_image2', models.ImageField(null=True, upload_to='home_banner/')),
                ('banner_image3', models.ImageField(null=True, upload_to='home_banner/')),
                ('banner_content1', models.CharField(max_length=200)),
                ('banner_content2', models.CharField(max_length=200)),
                ('banner_content3', models.CharField(max_length=200)),
                ('banner_description1', models.TextField()),
                ('banner_description2', models.TextField()),
                ('banner_description3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testinomials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(null=True, upload_to='home_profile/')),
                ('revied_by', models.CharField(choices=[('Interior designer', 'Interior designer'), ('Architect ', 'Architect'), ('Builder', 'Builder'), ('Customer', 'Customer')], max_length=50, null=True)),
                ('via', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Google', 'Google')], max_length=50, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
