# Generated by Django 3.1.2 on 2020-10-27 10:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_customer', models.BooleanField(default=False)),
                ('is_designer', models.BooleanField(default=False)),
                ('is_architect', models.BooleanField(default=False)),
                ('is_builder', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
                ('is_support_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SupportEnquries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('Requirements', models.TextField()),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SupportEnquiry',
                'verbose_name_plural': 'SupportEnquries',
            },
        ),
        migrations.CreateModel(
            name='Support_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('website', models.URLField(null=True)),
                ('company_address', models.TextField(null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_status', models.CharField(choices=[('Verifing', 'Verifing'), ('Details_required', 'Details_required'), ('Profile_created', 'Profile_created'), ('Awaiting_confiramtion', 'Awaiting_confiramtion'), ('Profile_live', 'Profile_live')], max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support_staff',
                'verbose_name_plural': 'Support_staffs',
            },
        ),
        migrations.CreateModel(
            name='DesignerEnquries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('Requirements', models.TextField()),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DesignerEnquiry',
                'verbose_name_plural': 'DesignerEnquries',
            },
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('website', models.URLField(null=True)),
                ('company_address', models.TextField(null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_status', models.CharField(choices=[('Verifing', 'Verifing'), ('Details_required', 'Details_required'), ('Profile_created', 'Profile_created'), ('Awaiting_confiramtion', 'Awaiting_confiramtion'), ('Profile_live', 'Profile_live')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Designer',
                'verbose_name_plural': 'Designers',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('professional_name', models.CharField(max_length=20)),
                ('file_type', models.CharField(choices=[('Design', 'Design'), ('Estimation', 'Estimation'), ('Quotation', 'Quotation'), ('Invoice', 'Invoice'), ('Bills', 'Bills')], max_length=50, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='')),
                ('Notes', models.TextField()),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CustomerCloud',
                'verbose_name_plural': 'CustomersCloud',
            },
        ),
        migrations.CreateModel(
            name='BuilderEnquries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('Requirements', models.TextField()),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BuilderEnquiry',
                'verbose_name_plural': 'BuilderEnquries',
            },
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('website', models.URLField(null=True)),
                ('company_address', models.TextField(null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_status', models.CharField(choices=[('Verifing', 'Verifing'), ('Details_required', 'Details_required'), ('Profile_created', 'Profile_created'), ('Awaiting_confiramtion', 'Awaiting_confiramtion'), ('Profile_live', 'Profile_live')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Builder',
                'verbose_name_plural': 'Builders',
            },
        ),
        migrations.CreateModel(
            name='ArchitectEnquries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('Requirements', models.TextField()),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ArchitectEnquiry',
                'verbose_name_plural': 'ArchitectEnquries',
            },
        ),
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('website', models.URLField(null=True)),
                ('company_address', models.TextField(null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_status', models.CharField(choices=[('Verifing', 'Verifing'), ('Details_required', 'Details_required'), ('Profile_created', 'Profile_created'), ('Awaiting_confiramtion', 'Awaiting_confiramtion'), ('Profile_live', 'Profile_live')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Architect',
                'verbose_name_plural': 'Architects',
            },
        ),
        migrations.CreateModel(
            name='AgentProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=20)),
                ('property_category', models.CharField(choices=[('Villa', 'Villa'), ('Flat', 'Flat'), ('Independent_house', 'Independent_house'), ('Cosharing', 'Cosharing')], max_length=50, null=True)),
                ('property_type', models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale')], max_length=50, null=True)),
                ('property_location', models.CharField(max_length=50, null=True)),
                ('upload_property_image', models.FileField(blank=True, null=True, upload_to='')),
                ('Description', models.TextField()),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AgentProperty',
                'verbose_name_plural': 'AgentProperties',
            },
        ),
        migrations.CreateModel(
            name='AgentEnquries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('Requirements', models.TextField()),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AgentEnquiry',
                'verbose_name_plural': 'AgentEnquries',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('website', models.URLField(null=True)),
                ('company_address', models.TextField(null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_status', models.CharField(choices=[('Verifing', 'Verifing'), ('Details_required', 'Details_required'), ('Profile_created', 'Profile_created'), ('Awaiting_confiramtion', 'Awaiting_confiramtion'), ('Profile_live', 'Profile_live')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='AddProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=20)),
                ('property_category', models.CharField(choices=[('Villa', 'Villa'), ('Flat', 'Flat'), ('Independent_house', 'Independent_house'), ('Cosharing', 'Cosharing')], max_length=50, null=True)),
                ('property_location', models.CharField(max_length=50, null=True)),
                ('upload_property_image', models.FileField(blank=True, null=True, upload_to='')),
                ('Description', models.TextField()),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AddProperty',
                'verbose_name_plural': 'AddProperties',
            },
        ),
    ]
